export const GET_COUNTRIES = "GET_COUNTRIES";
export const COUNTRY_DETAIL = "COUNTRY_DETAIL";



//SEARCHBAR
export const FILTER_BY_NAME = "FILTER_BY_NAME";

//FILTRADO
export const ORDER_INPUT_COUNTRIES = "ORDER_INPUT_COUNTRIES";
export const ORDER_INPUT_POPULATION = "ORDER_INPUT_POPULATION";
export const FILTER_INPUT_CONTINENT = "FILTER_INPUT_CONTINENT";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const FILTER_INPUT_ACTIVITY = "FILTER_INPUT_ACTIVITY";

export const CREATE_ACTIVITY = "CREATE_ACTIVITY";