export const GET_COUNTRIES = "GET_COUNTRIES";
export const COUNTRY_DETAIL = "COUNTRY_DETAIL";
export const GET_COUNTRY_NAME = "GET_COUNTRY_NAME";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const FILTER_BY_NAME = "FILTER_BY_NAME";